### ISSUE TITLE
contact_targets specified in Hiera constantly update

### ISSUE THREAD

**Issue by cwells** [cwells/puppet-pingdom#45]
```yaml
pingdom::users:
  'SRE PagerDuty':
    contact_targets:
      - email: sre@company.com
      - number: 555-123-1212
        countrycode: 1
```

```
Notice: /Stage[main]/Pingdom/Pingdom_user[SRE PagerDuty]/contact_targets: contact_targets changed

[{'email' => 'sre@company.com', 'id' => '2786428', 'severity' => 'HIGH'}, 
{'countrycode' => '1', 'id' => '2786431', 'number' => '555-123-1212', 'severity' => 'HIGH'}] 

to 

'{"email"=>"sre@company.com", :severitylevel=>"HIGH"} 
{"number"=>"555-123-1212", "countrycode"=>1, :severitylevel=>"HIGH"}'
```
Not sure why, as the `insync?` method deals with the differences seen above. 

Doesn't appear to happen with `puppet apply`. Figures.
